spring.application.name=entsoe-ai-service

server.port=8090

#entsoe.db-service.url=http://192.168.0.6:8087

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3

entsoe.price-analyzer.url=http://192.168.0.6:8088